[workspace]
resolver = "2"
members = [
	"examples/android",
	"examples/demo",
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/awtterpip/bevy_oxr"

[workspace.dependencies]
eyre = "0.6.2"
bevy = "0.13"
openxr = { path = "../openxrs/openxr" }
color-eyre = "0.6.2"

[package]
name = "bevy_oxr"
version = "0.1.0"
description = "Community crate for OpenXR in Bevy"
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["vulkan", "d3d12"]
force-link = ["openxr/linked"]
vulkan = ["wgpu-core/vulkan"]
d3d12 = ["wgpu-core/dx12", "dep:winapi", "dep:d3d12"]

[dependencies]
ash = "0.37.3"
bevy.workspace = true
eyre.workspace = true
futures-lite = "2.0.1"
mint = "0.5.9"
wgpu = "0.19"
wgpu-core = { version = "0.19" }
wgpu-hal = "0.19"

[target.'cfg(windows)'.dependencies]
openxr = { workspace = true, features = [ "linked", "static", "mint" ] }
winapi = { version = "0.3.9", optional = true }
d3d12 = { version = "0.19", features = ["libloading"], optional = true }

[target.'cfg(all(target_family = "unix", not(target_arch = "wasm32")) )'.dependencies]
openxr = { workspace = true, features = [ "mint" ] }

[target.'cfg(all(not(target_family = "unix"), not(target_arch = "wasm32")))'.dependencies]
openxr = { workspace = true, features = [ "mint", "static" ] }

[target.'cfg(target_os = "android")'.dependencies]
ndk-context = "0.1"
jni = "0.20"

[dev-dependencies]
color-eyre.workspace = true

[[example]]
name = "xr"
path = "examples/xr.rs"

[profile.release]
debug = true
